title: Create Missiles Wiki
email: wiki@createmissiles.com
description: This is the official site for CreateMissiles, where you can learn about the mod. Even though Pondering and JEI is a part of the mod, it is still nice to have a real site.
baseurl: ""
url: "https://createmissiles.com"
github_username: Woukie

theme: minima
